name: Unit Test
on:
  push:
    paths: app/**
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - uses: actions/checkout@v7
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 24 # lts
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Unit Test
        working-directory: app # Wichtig!!
        run: npm ci && npm run test
